=== Sortierung der Testschritte in einem Bereich

Der Schlüsselwert für die Sortierung der Testschritte kann aus bis zu drei Teilen zusammengesetzt sein:

[cols="1,2a",options="header"]
|===

|Name
|Beschreibung

|RuleEntryCount
|Wird bei jedem Eintritt in eine neue oder andere Regel hochgezählt

|StepType
|

[cols=",~",frame=none]
!===

!0
!Testschritt für die Testfall Vorbedingung

!1
!Testschritt aus einer Bedingung

!2
!Zwischenschritt

!3
!Testschritt aus einer Aktion

!4
!Testschritt für die Testfall Nachbedingung

!===

|Sid
|Sequenz- oder Sort-ID, wird intern für die Testschritte automatisch hochgezählt, so dass die "normale" Reihenfolge der Testschritte dieselbe ist, mit der die Testschritte bei der Berechnung durchlaufen wurden.

Die automatisch hochgezählte SID kann über die Testschritteigenschaft *_sid=nnn_* auch individuell gesetzt werden.

|===

Die folgenden Schlüssel-Zusammensetzungen und Ablagebereiche werden verwendet:

[cols="1,1,1,1",options="header"]
|===

|Scope
|Sid
|Schlüssel-Zusammensetzung
|Ablagebereich

|Global
|definiert
|StepType + Sid
|1) Global mit Sid

|Global
|nicht definiert
|intern hochgezählte Sid
|2) Global ohne Sid

|Rule
|definiert
|RuleEntryCount + StepType + Sid
|3) Testschritte

|Rule
|nicht definiert
|RuleEntryCount + StepType + xFF + intern hochgezählte Sid
|3) Testschritte

|===

Über die Testschritteigenschaft Sid=nnn kann unterschiedlichen Testschritten dieselbe Sid zugeordnet werden,
wodurch sich auch gezielt gleiche Werte für den Sortierschlüssel ergeben können.

In diesen Fällen wird nur der letzte durchlaufene Testschritt in den Testfall übernommen.

<<<