=== Aufbau eines Testfalles

* Eine *_Testfall-Vorbedingung_* bestehend aus
** Einem Bereich mit allen Vorbedingungen mit *_scope=global und sid_*, gefolgt von
** Einem Bereich mit allen Vorbedingungen mit *_scope=global ohne sid_*, gefolgt von
** Einem Bereich mit allen Vorbedingungen *_ohne scope_* (d.h. scope rule)

* Die Liste aller "nicht Vor- oder Nachbedingungs-Testschritte", d.h. *_Testanweisungen, Zwischenschritte und erwartete Ergebnisse_*, bestehend aus
** Einem Bereich mit allen Testschritten mit *_scope=global und sid_*, gefolgt von
** Einem Bereich mit allen Testschritten mit *_scope=global ohne sid_*, gefolgt von
** Einem Bereich mit allen Testschritten *_ohne scope_* (d.h. scope rule)

* Eine *_Testfall-Nachbedingung_* bestehend aus:
** Einem Bereich mit allen Nachbedingungen mit *_scope=global und sid_*, gefolgt von
** Einem Bereich mit allen Nachbedingungen mit *_scope=global ohne sid_*, gefolgt von
** Einem Bereich mit allen Nachbedingungen *_ohne scope_* (d.h. scope rule)

<<<